---
- hosts: locust_node
  vars:
    worker_count: 4
  become: yes
  tasks:
    - name: Installing dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Adding Docker's apt key 
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Installing Docker
      apt:
        name: docker-ce
        state: present

    - name: Gathering information
      shell: uname -s
      register: unames

    - name: Gathering information
      shell: uname -m
      register: unamem

    - name: Installing Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-{{ unames.stdout }}-{{ unamem.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensuring Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pulling Locust image
      docker_image:
        name: locustio/locust
        tag: latest
        source: pull

    - name: Ensuring Locust directory exists
      file:
        path: /tmp/locust
        state: directory
  
    - name: Creating Locust Docker Compose file
      copy:
        dest: /tmp/locust/docker-compose.yml
        content: |
          version: '3'
          services:
            master:
              image: locustio/locust
              ports:
                - "8089:8089"
              volumes:
                - ./:/mnt/locust
              command: -f /mnt/locust/locustfile.py --master -H http://master:8089
            worker:
              image: locustio/locust
              volumes:
                - ./:/mnt/locust
              command: -f /mnt/locust/locustfile.py --worker --master-host master


    - name: Creating locustfile.py
      copy:
        dest: /tmp/locust/locustfile.py
        content: |
          import time
          from locust import HttpUser, task, between

          class QuickstartUser(HttpUser):
            self.wait_time = between(100, 500)
            self.items = ["OLJCESPC7Z", "66VCHSJNUP", "1YMWWN1N4O", "L9ECAV7KIM", "2ZYFJ3GM2N", "0PUK6V6EV0", "LS4PSXUNUM", "9SIQT8TOJO", "6E92ZMYYFZ"]
    
            @task
            def homepage(self):
              self.client.get("/")

            @task
            def view_items(self):
              for elt in self.items:
                self.client.get("/product/"+elt)
                time.sleep(100)

    - name: Starting Locust with Docker Compose
      command: docker-compose up -d --scale worker={{ worker_count }}
      args:
        chdir: /tmp/locust
